### ISSUE TITLE
Marvin doesn't respond to the culturally accepted morning greeting "morrn".

### ISSUE THREAD

**Issue by ceruzaa** [mosbth/irc2phpbb#29]
Marvin lives in a place where "morrn" or "morrn morrn" is the culturally accepted greeting. I can only assume that it is a bug that Marvin does not respond when i type "marvin: morrn". 

This is an urgent bug. Please fix.

**Comment by mosbth** [comment]
Would be nice if marvin also said "morrn morrn"; but thats another issue. So off topic, sorry.
